version: '3.7'
services:

  nuxeo:
    image: nuxeo:10.10
    ports:
      - "8610:8080"
    environment:
      NUXEO_PACKAGES: nuxeo-web-ui nuxeo-showcase-content
      NUXEO_CUSTOM_PARAM: JAVA_OPTS=$$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n\nnuxeo.url=http://localhost:8610/nuxeo
    volumes:
      - ".gen/nuxeo_log:/var/log/"
      - ".gen/nuxeo_store:/opt/nuxeo/server/packages/store"
      - ".gen/nuxeo_data:/var/lib/nuxeo/data:cached"

  mongo:
    image: mongo
    #restart: always
    ports:
      - 8611:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ".gen/mongo_data:/data/db:cached"
